#!/bin/sh

job=/var/jb/Library/LaunchDaemons/de.akator.wurstvintedbridge.plist
launchctl bootout system/de.akator.wurstvintedbridge >/dev/null 2>&1 || true
launchctl bootstrap system "$job" >/dev/null 2>&1 || launchctl load "$job"
exit 0
