#!/usr/bin/env python3
"""Generates wurstfingerKeyboard/Runtime/Emoji/EmojiData+Generated.swift.

Reads Unicode's emoji-test.txt and keeps every fully-qualified emoji without
skin-tone modifiers, grouped like Android's emoji picker (which Thumb-Key
uses). Pin the version to the newest one the oldest supported iOS renders:
Emoji 15.0 ships with iOS 16.4 / 17.0; 15.1 needs iOS 17.4.

Usage: scripts/generate-emoji-data.py [path/to/emoji-test.txt]
Downloads https://unicode.org/Public/emoji/15.0/emoji-test.txt when no path is given.
"""

import pathlib
import sys
import urllib.request

VERSION = "15.0"
SKIN_TONES = {0x1F3FB, 0x1F3FC, 0x1F3FD, 0x1F3FE, 0x1F3FF}
# Unicode group -> (Swift case, SF Symbol for the tab)
GROUPS = {
    "Smileys & Emotion": ("smileys", "face.smiling"),
    "People & Body": ("people", "hand.raised"),
    "Animals & Nature": ("nature", "leaf"),
    "Food & Drink": ("food", "fork.knife"),
    "Travel & Places": ("travel", "car"),
    "Activities": ("activities", "soccerball"),
    "Objects": ("objects", "lightbulb"),
    "Symbols": ("symbols", "heart"),
    "Flags": ("flags", "flag"),
}


def main() -> None:
    if len(sys.argv) > 1:
        text = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
    else:
        url = f"https://unicode.org/Public/emoji/{VERSION}/emoji-test.txt"
        text = urllib.request.urlopen(url).read().decode("utf-8")

    groups: dict[str, list[str]] = {name: [] for name in GROUPS}
    current = None
    for line in text.splitlines():
        if line.startswith("# group:"):
            current = line.split(":", 1)[1].strip()
            continue
        if not line or line.startswith("#") or current not in GROUPS:
            continue
        codes, rest = line.split(";", 1)
        if rest.split("#", 1)[0].strip() != "fully-qualified":
            continue
        points = [int(code, 16) for code in codes.split()]
        if SKIN_TONES.intersection(points):
            continue
        groups[current].append("".join(chr(point) for point in points))

    out = [
        "//",
        "//  EmojiData+Generated.swift",
        "//  Wurstfinger",
        "//",
        f"//  Generated by scripts/generate-emoji-data.py from Unicode emoji-test.txt {VERSION}.",
        "//  Do not edit by hand.",
        "//",
        "",
        "// swiftlint:disable line_length",
        "",
        "extension EmojiCategory {",
        "    /// Space-separated emoji per category, in CLDR order.",
        "    static let generated: [EmojiCategory] = [",
    ]
    for name, (case, symbol) in GROUPS.items():
        joined = " ".join(groups[name])
        out.append(f'        EmojiCategory(id: "{case}", symbolName: "{symbol}", packed: "{joined}"),')
    out += ["    ]", "}", "", "// swiftlint:enable line_length", ""]

    target = pathlib.Path(__file__).resolve().parent.parent / "wurstfingerKeyboard/Runtime/Emoji/EmojiData+Generated.swift"
    target.write_text("\n".join(out), encoding="utf-8")
    counts = ", ".join(f"{GROUPS[name][0]} {len(items)}" for name, items in groups.items())
    print(f"Wrote {target} ({counts})")


if __name__ == "__main__":
    main()
